using Microsoft.Maui.Controls.Shapes;
using Zubrilka.Behaviors;
using Zubrilka.Models;
using Zubrilka.ViewModels;

namespace Zubrilka.Views;

public partial class PlaybackPage : ContentPage
{
    // Tint applied to the pane whose phrase is currently being spoken.
    private static readonly Color ActivePaneColor = Color.FromArgb("#332B7FFF");

    private readonly PlaybackViewModel _viewModel;
    private bool _started;

    public PlaybackPage(PlaybackViewModel viewModel)
    {
        InitializeComponent();
        BindingContext = _viewModel = viewModel;
        _viewModel.ExitRequested += OnExitRequested;
    }

    /// <summary>Supplies the block to play. Call before navigating to this page.</summary>
    public void Initialize(Block block) => _viewModel.Initialize(block);

    protected override async void OnAppearing()
    {
        base.OnAppearing();
        // Prepare once, even if the page re-appears.
        if (_started) return;
        _started = true;

        await _viewModel.PrepareAsync();  // settings, panes, voice check, shuffled cards
        BuildPanes();                     // lay out one section per language
        _viewModel.StartLoop();           // only now start showing/speaking
    }

    protected override async void OnNavigatedFrom(NavigatedFromEventArgs args)
    {
        base.OnNavigatedFrom(args);
        // Stop only on real navigation away (Exit, back arrow, hardware back).
        // Deliberately NOT OnDisappearing: that also fires when the app is merely backgrounded,
        // and playback must survive the screen being switched off or an app switch.
        await _viewModel.StopAsync();
    }

    private async void OnExitRequested()
        => await Navigation.PopAsync();

    /// <summary>
    /// Builds the pane layout: for each language a small caption row (which doubles as the
    /// separator between panes) and a star-sized box holding the phrase. Star rows share the
    /// available height equally, so the phrase box gets the full height minus the captions.
    /// </summary>
    private void BuildPanes()
    {
        PanesGrid.Clear();
        PanesGrid.RowDefinitions.Clear();

        int row = 0;
        foreach (var pane in _viewModel.Panes)
        {
            PanesGrid.RowDefinitions.Add(new RowDefinition(GridLength.Auto)); // caption
            PanesGrid.RowDefinitions.Add(new RowDefinition(GridLength.Star)); // phrase

            // Language code sits above its box, on the separator line, so it costs the
            // phrase no text room at all.
            var caption = new Label
            {
                Text = pane.Code,
                FontSize = 12,
                Opacity = 0.6,
                Padding = new Thickness(4, 6, 4, 2),
            };
            Grid.SetRow(caption, row++);
            PanesGrid.Add(caption);

            PanesGrid.Add(BuildPhraseBox(pane), 0, row++);
        }
    }

    // One bordered box showing a single language's phrase.
    private static Border BuildPhraseBox(LanguagePane pane)
    {
        var label = new Label
        {
            HorizontalTextAlignment = TextAlignment.Center,
            VerticalTextAlignment = TextAlignment.Center,
            LineBreakMode = LineBreakMode.WordWrap,
            // RTL scripts (Hebrew, Arabic, …) read right-to-left.
            FlowDirection = pane.Rtl ? FlowDirection.RightToLeft : FlowDirection.LeftToRight,
        };
        // Bind by name: Text is generated by [ObservableProperty], which the compiled-binding
        // source generator cannot resolve through a lambda path.
        label.SetBinding(Label.TextProperty, new Binding(nameof(LanguagePane.Text)));
        // Shrink the phrase only as far as needed to fit this box.
        label.Behaviors.Add(new FitFontBehavior { MaxFontSize = pane.MaxFontSize, MinFontSize = 12 });

        var border = new Border
        {
            Padding = 8,
            StrokeThickness = 1,
            StrokeShape = new RoundRectangle { CornerRadius = 10 },
            Content = label,
            BindingContext = pane,
        };

        // Highlight the pane being spoken right now.
        border.Triggers.Add(new DataTrigger(typeof(Border))
        {
            Binding = new Binding(nameof(LanguagePane.IsActive)),
            Value = true,
            Setters = { new Setter { Property = BackgroundColorProperty, Value = ActivePaneColor } },
        });

        return border;
    }
}
